<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="C02DCP4XML7H" name="com.hrm.qa.tests.RecruitmentTest" tests="5" failures="1" timestamp="2022-10-08T16:11:28 IST" time="70.902" errors="0">
  <testcase name="validateRecruitmentPageTitle" time="14.051" classname="com.hrm.qa.tests.RecruitmentTest">
    <skipped/>
  </testcase> <!-- validateRecruitmentPageTitle -->
  <system-out/>
  <testcase name="validateRecruitmentPageTitle" time="10.918" classname="com.hrm.qa.tests.RecruitmentTest">
    <skipped/>
  </testcase> <!-- validateRecruitmentPageTitle -->
  <system-out/>
  <testcase name="validateRecruitmentPageTitle" time="11.610" classname="com.hrm.qa.tests.RecruitmentTest">
    <failure type="java.lang.AssertionError" message="expected [Recruitments] but found [Recruitment]">
      <![CDATA[java.lang.AssertionError: expected [Recruitments] but found [Recruitment]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.hrm.qa.tests.RecruitmentTest.validateRecruitmentPageTitle(RecruitmentTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateRecruitmentPageTitle -->
  <system-out/>
  <testcase name="enterCandidateCredentials" time="17.323" classname="com.hrm.qa.tests.RecruitmentTest"/>
  <system-out/>
  <testcase name="enterCandidateCredentials" time="17.000" classname="com.hrm.qa.tests.RecruitmentTest"/>
  <system-out/>
</testsuite> <!-- com.hrm.qa.tests.RecruitmentTest -->
